apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-nrhxyb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-nrhxyb
    app.kubernetes.io/part-of: jvm-build-suite-application-ildx
  name: jvm-build-suite-component-nrhxyb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-nrhxyb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-nrhxyb
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/jvm-build-dotm-tenant/jvm-build-suite-application-ildx/jvm-build-suite-component-nrhxyb@sha256:2a36b2629223c799bda78dbcca2e722eec66d18b9ccc9bd0d751179e3434fc87
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
